Bubble sort
lekegitrepo/bubble-sort-algorithms pull request #1
Opened 2019-09-17 20:30 UTC by lekegitrepo

2019-09-17 21:54 UTC, maelfosso requested changes
Hello @lekegitrepo @noomdalv 

:clap: Thank you that beautiful code :smile: 
There is one function that you forgot to implement `bubble_sort_by`.

Please kindly implement it and submit a new code review request.
Thanks

2019-09-18 18:57 UTC, samgaco approved these changes
Hi @lekegitrepo and @noomdalv :high_brightness: 

The project is approved :white_check_mark: . You may merge to the master branch and submit the project completion form.

-----------------
**[Has to be addressed]** :warning: 
* May I ask about whether you are working in pairs or not? There is only one commit by @noomdalv , the projects should be done in pairs taking turns of 35 to 45 minutes. Please address this issue or contact student success if you are dealing with any issues.
-----------------
moving on bear this in mind :arrow_down: 

* **[For your next code review requests]**  Add a short summary of changes in Pull Request description

----------------------

* ###### STATUS OF THE PROJECT: APPROVED :heavy_check_mark:

2019-09-18 18:57 UTC, samgaco commented on bubble_sort.rb
> +end
You forgot to take off this test case

2019-09-18 18:57 UTC, samgaco commented on bubble_sort.rb
> +  p arr
the "p" is not needed

2019-09-18 20:04 UTC, merged